"""empty message

Revision ID: 01d1bcbd1994
Revises: 733b628a2377
Create Date: 2018-05-10 13:38:59.865362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d1bcbd1994'
down_revision = '733b628a2377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('poster_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter', 'poster_url')
    # ### end Alembic commands ###
