"""empty message

Revision ID: ffe0541a1c04
Revises: 9efa0b7fa50c
Create Date: 2018-05-12 10:32:05.964566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe0541a1c04'
down_revision = '9efa0b7fa50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('added_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter', 'added_time')
    # ### end Alembic commands ###
